# Generated by Django 4.0.2 on 2022-02-03 09:37

from django.db import migrations, models
import zoolanding.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', validators=[zoolanding.models.MaxSizeValidator(1)], verbose_name='картинка')),
                ('description', models.TextField(max_length=255, verbose_name='описание')),
            ],
        ),
    ]
