# Generated by Django 4.0.2 on 2022-02-10 09:48

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название акции')),
                ('image', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='картинка')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание акции')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_services', models.CharField(max_length=250, verbose_name='Название услуги')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание услуги')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['name_services'],
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(max_length=250, verbose_name='Наименование услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоимость, бел. руб.')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service', to='zoolanding.services', verbose_name='Категория услуг')),
            ],
            options={
                'verbose_name': 'Наименование услуги',
                'verbose_name_plural': 'Наименование услуг',
                'ordering': ['name_of_service', 'price'],
            },
        ),
    ]
