# Generated by Django 4.0.2 on 2022-02-03 11:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoolanding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'акция', 'verbose_name_plural': 'акции'},
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
