# Generated by Django 4.0.2 on 2022-02-03 18:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoolanding', '0002_alter_action_options_alter_action_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_services', models.CharField(max_length=250, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name_services'],
            },
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='описание'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(max_length=250, verbose_name='Наименование услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоимость, бел. руб.')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service', to='zoolanding.services')),
            ],
            options={
                'verbose_name': 'Наименование услуги',
                'verbose_name_plural': 'Наименование услуг',
                'ordering': ['name_of_service', 'price'],
            },
        ),
    ]
